name       : xcb-util-cursor
version    : 0.1.3
release    : 2
source     :
    - https://xcb.freedesktop.org/dist/xcb-util-cursor-0.1.3.tar.gz : a322332716a384c94d3cbf98f2d8fe2ce63c2fe7e2b26664b6cea1d411723df8
license    : MIT
component  : xorg.library
summary    : XCB util-cursor module provides a port of libxcursor.
description: |
    XCB util-cursor module provides a port of libxcursor.
builddeps  :
    - pkgconfig(xcb-image)
    - pkgconfig(xcb-render)
    - pkgconfig(xcb-renderutil)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
