name       : xcb-util-cursor
version    : 0.1.4
release    : 4
source     :
    - https://xcb.freedesktop.org/dist/xcb-util-cursor-0.1.4.tar.gz : cc8608ebb695742b6cf84712be29b2b66aa5f6768039528794fca0fa283022bf
license    : MIT
component  : xorg.library
summary    : XCB util-cursor module provides a port of libxcursor.
description: |
    XCB util-cursor module provides a port of libxcursor.
builddeps  :
    - pkgconfig(xcb-image)
    - pkgconfig(xcb-render)
    - pkgconfig(xcb-renderutil)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
